<cn.myapps.core.workflow.element.FlowDiagram>
<ACTION_NORMAL>0</ACTION_NORMAL>
<ACTION_REMOVE>1</ACTION_REMOVE>
<ACTION_ADD_ABORTNODE>16</ACTION_ADD_ABORTNODE>
<ACTION_ADD_AUTONODE>17</ACTION_ADD_AUTONODE>
<ACTION_ADD_COMPLETENODE>18</ACTION_ADD_COMPLETENODE>
<ACTION_ADD_MANUALNODE>19</ACTION_ADD_MANUALNODE>
<ACTION_ADD_STARTNODE>20</ACTION_ADD_STARTNODE>
<ACTION_ADD_SUSPENDNODE>21</ACTION_ADD_SUSPENDNODE>
<ACTION_ADD_TERMINATENODE>22</ACTION_ADD_TERMINATENODE>
<ACTION_ADD_RELATION>4096</ACTION_ADD_RELATION>
<ACTION_EDIT_NODE>268435472</ACTION_EDIT_NODE>
<ACTION_EDIT_RELATION>268439552</ACTION_EDIT_RELATION>
<ACTION_BREAK_LINE>1048576</ACTION_BREAK_LINE>
<flowstatus>16</flowstatus>
<flowpath></flowpath>
<deleteMSG>null</deleteMSG>
<width>2048</width>
<height>1536</height>
<_applicationid>null</_applicationid>
<_sessionid>null</_sessionid>
<TOP_ALIGNMENT>0.0</TOP_ALIGNMENT>
<CENTER_ALIGNMENT>0.5</CENTER_ALIGNMENT>
<BOTTOM_ALIGNMENT>1.0</BOTTOM_ALIGNMENT>
<LEFT_ALIGNMENT>0.0</LEFT_ALIGNMENT>
<RIGHT_ALIGNMENT>1.0</RIGHT_ALIGNMENT>
<WIDTH>1</WIDTH>
<HEIGHT>2</HEIGHT>
<PROPERTIES>4</PROPERTIES>
<SOMEBITS>8</SOMEBITS>
<FRAMEBITS>16</FRAMEBITS>
<ALLBITS>32</ALLBITS>
<ERROR>64</ERROR>
<ABORT>128</ABORT>

<cn.myapps.core.workflow.element.StartNode>
<prenodeid></prenodeid>
<statelabel>Start</statelabel>
<backnodeid></backnodeid>
<formname></formname>
<fieldpermlist></fieldpermlist>
<isstartandnext>false</isstartandnext>
<x>50</x>
<y>150</y>
<width>46</width>
<height>55</height>
<_iscurrent>false</_iscurrent>
<scale>0</scale>
<name>start</name>
<note></note>
<id>1203931561240</id>
</cn.myapps.core.workflow.element.StartNode>

<#list nodeInfo as n>
<cn.myapps.core.workflow.element.ManualNode>
<namelist>${n.nodeRole}</namelist>
<realnamelist></realnamelist>
<passcondition>0</passcondition>
<exceedaction>0</exceedaction>
<sendmodelist></sendmodelist>
<timeunit>0</timeunit>
<isnotifysuperior>false</isnotifysuperior>
<istimelimit>false</istimelimit>
<notifiable>false</notifiable>
<actorListScript></actorListScript>
<actorEditMode>0</actorEditMode>
<inputform></inputform>
<isgather>false</isgather>
<issplit>false</issplit>
<prenodeid></prenodeid>
<statelabel><#if n_index==0>Draft<#else>Running</#if></statelabel>
<backnodeid></backnodeid>
<formname></formname>
<notificationStrategyJSON>{}</notificationStrategyJSON>
<PASS_CONDITION_OR>0</PASS_CONDITION_OR>
<PASS_CONDITION_AND>1</PASS_CONDITION_AND>
<PASS_CONDITION_ORDERLY_AND>2</PASS_CONDITION_ORDERLY_AND>
<ACTOR_EDIT_MODE_DESIGN>0</ACTOR_EDIT_MODE_DESIGN>
<ACTOR_EDIT_MODE_CODE>1</ACTOR_EDIT_MODE_CODE>
<fieldpermlist></fieldpermlist>
<isstartandnext>false</isstartandnext>
<x><#if n_index % 2 == 0>175<#else>300</#if></x>
<y><#if n_index<=1>25<#else>250</#if></y>
<width>46</width>
<height>55</height>
<_iscurrent>false</_iscurrent>
<scale>0</scale>
<name>${n.nodeName}</name>
<note></note>
<id>120393156124${n_index+1}</id>
</cn.myapps.core.workflow.element.ManualNode>
</#list>

<cn.myapps.core.workflow.element.CompleteNode>
<prenodeid></prenodeid>
<statelabel>Finished</statelabel>
<backnodeid></backnodeid>
<formname></formname>
<fieldpermlist></fieldpermlist>
<isstartandnext>false</isstartandnext>
<x>425</x>
<y>150</y>
<width>46</width>
<height>55</height>
<_iscurrent>false</_iscurrent>
<scale>0</scale>
<name>end</name>
<note></note>
<id>1203931561245</id>
</cn.myapps.core.workflow.element.CompleteNode>
<cn.myapps.core.workflow.element.Relation>
<state></state>
<startnodeid>1203931561240</startnodeid>
<endnodeid>1203931561241</endnodeid>
<ispassed>false</ispassed>
<isreturn>false</isreturn>
<condition></condition>
<filtercondition></filtercondition>
<editMode></editMode>
<processDescription></processDescription>
<action></action>
<pointstack>50;150;175;25</pointstack>
<EDITMODE_VIEW>00</EDITMODE_VIEW>
<EDITMODE_CODE>01</EDITMODE_CODE>
<validateScript></validateScript>
<scale>0</scale>
<name></name>
<note></note>
<id>1203931671310</id>
</cn.myapps.core.workflow.element.Relation>
<cn.myapps.core.workflow.element.Relation>
<state></state>
<startnodeid>1203931561240</startnodeid>
<endnodeid>1203931561243</endnodeid>
<ispassed>false</ispassed>
<isreturn>false</isreturn>
<condition></condition>
<filtercondition></filtercondition>
<editMode></editMode>
<processDescription></processDescription>
<action></action>
<pointstack>50;150;175;250</pointstack>
<EDITMODE_VIEW>00</EDITMODE_VIEW>
<EDITMODE_CODE>01</EDITMODE_CODE>
<validateScript></validateScript>
<scale>0</scale>
<name></name>
<note></note>
<id>1203931673152</id>
</cn.myapps.core.workflow.element.Relation>
<cn.myapps.core.workflow.element.Relation>
<state></state>
<startnodeid>1203931561241</startnodeid>
<endnodeid>1203931561242</endnodeid>
<ispassed>false</ispassed>
<isreturn>false</isreturn>
<condition></condition>
<filtercondition></filtercondition>
<editMode></editMode>
<processDescription></processDescription>
<action></action>
<pointstack>175;25;300;25</pointstack>
<EDITMODE_VIEW>00</EDITMODE_VIEW>
<EDITMODE_CODE>01</EDITMODE_CODE>
<validateScript></validateScript>
<scale>0</scale>
<name></name>
<note></note>
<id>1203931677459</id>
</cn.myapps.core.workflow.element.Relation>
<cn.myapps.core.workflow.element.Relation>
<state></state>
<startnodeid>1203931561243</startnodeid>
<endnodeid>1203931561244</endnodeid>
<ispassed>false</ispassed>
<isreturn>false</isreturn>
<condition></condition>
<filtercondition></filtercondition>
<editMode></editMode>
<processDescription></processDescription>
<action></action>
<pointstack>175;250;300;250</pointstack>
<EDITMODE_VIEW>00</EDITMODE_VIEW>
<EDITMODE_CODE>01</EDITMODE_CODE>
<validateScript></validateScript>
<scale>0</scale>
<name></name>
<note></note>
<id>1203931679872</id>
</cn.myapps.core.workflow.element.Relation>
<cn.myapps.core.workflow.element.Relation>
<state></state>
<startnodeid>1203931561242</startnodeid>
<endnodeid>1203931561245</endnodeid>
<ispassed>false</ispassed>
<isreturn>false</isreturn>
<condition></condition>
<filtercondition></filtercondition>
<editMode></editMode>
<processDescription></processDescription>
<action></action>
<pointstack>300;25;425;150</pointstack>
<EDITMODE_VIEW>00</EDITMODE_VIEW>
<EDITMODE_CODE>01</EDITMODE_CODE>
<validateScript></validateScript>
<scale>0</scale>
<name></name>
<note></note>
<id>1203931683217</id>
</cn.myapps.core.workflow.element.Relation>
<cn.myapps.core.workflow.element.Relation>
<state></state>
<startnodeid>1203931561244</startnodeid>
<endnodeid>1203931561245</endnodeid>
<ispassed>false</ispassed>
<isreturn>false</isreturn>
<condition></condition>
<filtercondition></filtercondition>
<editMode></editMode>
<processDescription></processDescription>
<action></action>
<pointstack>300;250;425;150</pointstack>
<EDITMODE_VIEW>00</EDITMODE_VIEW>
<EDITMODE_CODE>01</EDITMODE_CODE>
<validateScript></validateScript>
<scale>0</scale>
<name></name>
<note></note>
<id>1203931685640</id>
</cn.myapps.core.workflow.element.Relation>
</cn.myapps.core.workflow.element.FlowDiagram>