-- 版本2310后需增加以下字段, 对应不同数据库的实现
-- Oracle
alter table T_ACTORRT add (DEADLINE TIMESTAMP(6), DOMAINID VARCHAR2(255 CHAR));
alter table T_NODERT add (NOTIFIABLE NUMBER(1,0), DOMAINID VARCHAR2(255 CHAR));
alter table T_RELATIONHIS add AUDITOR VARCHAR2(255);
alter table T_DOCUMENT add MAPPINGID VARCHAR2(255);
-- DB2
alter table schema.T_ACTORRT add DEADLINE TIMESTAMP;
alter table schema.T_ACTORRT add DOMAINID VARCHAR(255);
alter table schema.T_NODERT add NOTIFIABLE DECIMAL(1,0);
alter table schema.T_NODERT add DOMAINID VARCHAR(255);
alter table schema.T_RELATIONHIS add AUDITOR VARCHAR(255);
alter table T_DOCUMENT add MAPPINGID VARCHAR(255);
-- MSSQL
alter table T_ACTORRT add DEADLINE DATETIME;
alter table T_ACTORRT add DOMAINID NVARCHAR(200);
alter table T_NODERT add NOTIFIABLE BIT;
alter table T_NODERT add DOMAINID NVARCHAR(200)
alter table T_RELATIONHIS add AUDITOR NVARCHAR(255);
alter table T_DOCUMENT add MAPPINGID NVARCHAR(255);
-- MYSQL
alter table T_ACTORRT add (DEADLINE TIMESTAMP(6), DOMAINID VARCHAR(255));
alter table T_NODERT add (NOTIFIABLE BIT(1), DOMAINID VARCHAR(255));
alter table T_RELATIONHIS add AUDITOR VARCHAR(255);
alter table T_DOCUMENT add MAPPINGID VARCHAR(255);
-- HypersonicSQL
alter table T_ACTORRT add (DEADLINE DATE, DOMAINID VARCHAR(200));
alter table T_NODERT add (NOTIFIABLE BIT, DOMAINID VARCHAR(200));
alter table T_RELATIONHIS add AUDITOR VARCHAR(255);
alter table T_DOCUMENT add MAPPINGID VARCHAR(255);