document.write('<!-- 用来产生编辑状态的ActiveX控件的JS脚本-->');
document.write('<!-- 因为微软的ActiveX新机制，需要一个外部引入的js--> ');
document.write('<object id="TANGER_OCX" classid="clsid:A39F1330-3322-4a1d-9BF0-0BA2BB90E970"');
document.write('codebase="../../dynaform/form/word/OfficeControl.cab#version=5,0,1,0" width="100%" height="100%">');
document.write('<param name="isuseutf8url" value="-1">');
document.write('<param name="IsUseUTF8Data" value="-1">');
document.write('<param name="BorderStyle" value="1">');
document.write('<param name="BorderColor" value="14402205">');
document.write('<param name="TitlebarColor" value="15658734">');
document.write('<param name="TitlebarTextColor" value="0">');
document.write('<param name="MenubarColor" value="14402205">');
document.write('<param name="MenuButtonColor" VALUE="16180947">');
document.write('<param name="MenuBarStyle" value="3">');
document.write('<param name="MenuButtonStyle" value="7">');
document.write('<param name="WebUserName" value="NTKO">');
document.write('<param name="MakerCaption" value="广州市天翎网络科技有限公司">');
document.write('<param name="MakerKey" value="043AE2EC6226BA75F8B613E36DF6A8FE77BB5650">');
document.write('<param name="ProductCaption" value="广州市天翎网络科技有限公司内部使用版">'); 
document.write('<param name="ProductKey" value="78EFBA909C0D64EE96C11AAB9FB45C6C3F006816">');
document.write('<SPAN STYLE="color:red">{*[page.can.not.load.document]*}!{*[page.check.browser.security.settings]*}!</SPAN>');
document.write('</object>');