UPDATE obpm.t_domain SET WEIXIN_CORP_ID='wxc762198eb8bb3538',
WEIXIN_CORP_SECRET='cxCBlRMB4LSaUX2VGVR6PE_PY__nrW0E7tI-56ZTZHRvY75XmQSC-m8FTf1UACdz',WEIXIN_AGENT_ID='19',
WEIXIN_TOKEN='KbYueyQ1lQxWuSo',WEIXIN_ENCODING_AESKEY='VudEq2rh2Lh1TIi1fBjDOKpQucg1ZzSqXGV4toOvKiG',
WEIXIN_PROXY_TYPE='local',
SERVER_HOST='http://dev01.teemlink.com:8080/obpm/';
UPDATE obpm.t_usersetup SET USERSKIN='H5';
UPDATE obpm.t_superuser set LOGINPWD='TeemlinK' where LOGINNO='admin' or LOGINNO='developer'
